export const CREATE_FIELD_REQUEST = "CREATE_FIELD_REQUEST";
export const CREATE_FIELD_SUCCESS = "CREATE_FIELD_SUCCESS";
export const CREATE_FIELD_FAIL = "CREATE_FIELD_FAIL";
export const CREATE_FIELD_RESET = "CREATE_FIELD_RESET";

export const UPDATE_FIELD_REQUEST = "UPDATE_FIELD_REQUEST";
export const UPDATE_FIELD_SUCCESS = "UPDATE_FIELD_SUCCESS";
export const UPDATE_FIELD_FAIL = "UPDATE_FIELD_FAIL";
export const UPDATE_FIELD_RESET = "UPDATE_FIELD_RESET";

export const DELETE_FIELD_REQUEST = "DELETE_FIELD_REQUEST";
export const DELETE_FIELD_SUCCESS = "DELETE_FIELD_SUCCESS";
export const DELETE_FIELD_FAIL = "DELETE_FIELD_FAIL";
export const DELETE_FIELD_RESET = "DELETE_FIELD_RESET";

export const GET_FIELD_REQUEST = "GET_FIELD_REQUEST";
export const GET_FIELD_SUCCESS = "GET_FIELD_SUCCESS";
export const GET_FIELD_FAIL = "GET_FIELD_FAIL";
export const GET_FIELD_RESET = "GET_FIELD_RESET";

export const GET_FIELDS_REQUEST = "GET_FIELDS_REQUEST";
export const GET_FIELDS_SUCCESS = "GET_FIELDS_SUCCESS";
export const GET_FIELDS_FAIL = "GET_FIELDS_FAIL";
export const GET_FIELDS_RESET = "GET_FIELDS_RESET";
