export const CREATE_S2_NDVI_REQUEST = "CREATE_S2_NDVI_REQUEST";
export const CREATE_S2_NDVI_SUCCESS = "CREATE_S2_NDVI_SUCCESS";
export const CREATE_S2_NDVI_FAIL = "CREATE_S2_NDVI_FAIL";
export const CREATE_S2_NDVI_RESET = "CREATE_S2_NDVI_RESET";

export const CREATE_L8_NDVI_REQUEST = "CREATE_L8_NDVI_REQUEST";
export const CREATE_L8_NDVI_SUCCESS = "CREATE_L8_NDVI_SUCCESS";
export const CREATE_L8_NDVI_FAIL = "CREATE_L8_NDVI_FAIL";
export const CREATE_L8_NDVI_RESET = "CREATE_L8_NDVI_RESET";
